### ISSUE TITLE
WASI-SDK with alternate toolchain

### ISSUE THREAD

**Issue by pchickey** [fastly/lucet#110]
In https://github.com/fastly/lucet/issues/104, a user struggled with configuring lucet-wasi to use the release llvm 8 toolchain with the wasi-sdk provided sysroot.

We should support using the wasi-sdk sysroot with whatever toolchain the user wants.

**Comment by jedisct1** [comment]
The only missing piece to get the wasi-sdk sysroot work with a stock LLVM 8 toolchain is the Clang set of builtins for WASI.

https://github.com/jedisct1/libclang_rt.builtins-wasm32.a

**Comment by pchickey** [comment]
The builtins should be the same across all wasm32 targets, not specific to wasi, correct? Could we work with clang upstream to get them to ship the wasm32 builtins as part of the toolchain, like they do (presumably) for other platforms? cc @sunfishcode

**Comment by sunfishcode** [comment]
I don't think clang upstream ships builtins libraries for cross-compiling for any platform. For example, the packages [here](http://releases.llvm.org/download.html#8.0.0) don't, afaict.

**Comment by jedisct1** [comment]
Would having the pre-compiled builtins available for download in some non-personal repository be an option?

**Comment by pchickey** [comment]
I don't see why we couldn't release those binaries as part of wasi-sdk releases. Want to make a PR there that adds a tar of those builtins to the build output?

**Comment by jedisct1** [comment]
Done.
