### ISSUE TITLE
Lack of "_start" export causes exception. Use standard (start ...) instead

### ISSUE THREAD

**Issue by kanaka** [fastly/lucet#129]
lucet appears to assume that a wasm module exports a "_start" function. This should either be optional or dropped since (start ...) is already supported and is called before the exported "_start" routine.

The following wat file:

```
(module
  (memory 256)
  (export "memory" (memory 0))

  (import "wasi_unstable" "fd_write" (func $fd_write (param i32 i32 i32 i32) (result i32)))

  ;; __wasi_ciovec_t struct
  (data (i32.const 0) "\08\00\00\00") ;; buf: pointer to hello string
  (data (i32.const 4) "\0c\00\00\00") ;; buf_len: 12 characters
  ;; string
  (data (i32.const 8) "hello world\n")

  (func $main
    (drop (call $fd_write (i32.const 1) (i32.const 0) (i32.const 1) (i32.const 64)))
  )

  (start $main)
  ;;(export "_start" $main)
)
```

Will result in the following:

```
# RUST_BACKTRACE=1 /opt/lucet/bin/lucet-wasi wasitests/start.so
hello world
thread 'main' panicked at 'lucet-wasi runtime error: Symbol not found: _start', lucet-wasi/src/main.rs:196:23
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:340
   7: lucet_wasi::main
   8: std::rt::lang_start::{{closure}}
   9: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  10: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:92
  11: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  12: main
  13: __libc_start_main
  14: _start
```

Note that the function specified by (start) is being called and then the exception is thrown. If both (start) and exported "_start" are used (uncomment export above) then the main function is executed twice as follows:

```
# RUST_BACKTRACE=1 /opt/lucet/bin/lucet-wasi wasitests/start.so
hello world
hello world

```
I think lucet should not require "_start" to be exported since this functionality is already supported by the standard (start) mechanism.

**Comment by sunfishcode** [comment]
There is a subtlety here: at the time when the wasm start function is called, code outside the module cannot access the module's exports. So if the wasm start function calls some code that expects to be able to call back into the wasm, it won't work. It remains an open question whether such cyclic dependency patterns should be supported in wasm. The WASI libc uses an exported function named `_start` right now, instead of a wasm start function, to avoid these issues.

**Comment by kanaka** [comment]
@sunfishcode ah, because the start function is intended to be called during instantiation of the module right? That makes sense. So I guess the real issue is that lucet is throwing an exception when "_start" isn't exported whereas wasmtime is not (or it is but is swallowing the exception). Also, perhaps a different name than "_start" so it doesn't get as easily confused with the start function (like it did for me)? "_main" or "_entry" perhaps?

**Comment by sunfishcode** [comment]
I agree, `_start` is confusing. I filed https://github.com/WebAssembly/WASI/issues/19 to track changing the name.

**Comment by acfoltzer** [comment]
I'm going to close this for now; we'll be sure to adapt what `lucet-wasi` does to match the behavior that results from the WebAssembly/WASI#19 discussion. Until then, we will need to keep the current behavior of running the wasm start function on instantiation, and then calling an exported `_start` function for the main program.
