### ISSUE TITLE
Move all the documentation to a Wiki

### ISSUE THREAD

**Issue by jedisct1** [fastly/lucet#134]
The main `README` file just gives the big picture, yet it is way too long.

The quickstart instructions difficult to find. Other `README` files are hidden in subfolders.

Not sure that anybody has noticed the document about Lucet's security model.

Maybe we should consider moving all the documentation to the Wiki section, so that everything can be at the same place, and people can quickly get the info they are looking for.

**Comment by jedisct1** [comment]
Bumping that one up, because the main README file is about to get even longer and messier.

Do we agree to move all the documentation to the Wiki?

**Comment by pchickey** [comment]
Go for it!

**Comment by jedisct1** [comment]
👍

**Comment by jedisct1** [comment]
Closing this ticket, then.

I'm going to take care of this.
