### ISSUE TITLE
Compiled .so file missing ELF .data section, likely due to integer overflow in Faerie

### ISSUE THREAD

**Issue by zhuowei** [fastly/lucet#141]
I have a [WASM file](https://drive.google.com/file/d/1Iz4eSvyeZRJrpDOcN7bkAYXdKlYcEh-x/view?usp=sharing) that has extra data segments, and Lucet compiles it into an invalid .so file.

I'm using a [slightly modified Lucet](https://github.com/swiftwasm/lucet/tree/swiftwasm) that adds stub functions for the unimplemented parts of WASI, but I don't think that's causing the issue here.

```
$ /opt/lucet/bin/lucetc-wasi -o hello.so hello.wasm
$ /opt/lucet/bin/lucet-wasi hello.so 
thread 'main' panicked at 'module can be loaded: ModuleError(IncorrectModule("error loading required symbol `lucet_module_data`: /home/zhuowei/swift-source/build/Ninja-RelWithDebInfoAssert/swift-linux-x86_64/bin/hello.so: undefined symbol: lucet_module_data"))', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

`objdump -T hello.so` shows that the symbol is defined, but doesn't have a section:
`0000000000000000 g    DO *ABS*  00000000000c0745 lucet_module_data`

`objdump -x hello.so` shows that the entire .data section is missing:
```
hello.so:     file format elf64-x86-64
hello.so
architecture: i386:x86-64, flags 0x00000150:
HAS_SYMS, DYNAMIC, D_PAGED
start address 0x00000000003d58b0

Program Header:
    LOAD off    0x0000000000000000 vaddr 0x0000000000000000 paddr 0x0000000000000000 align 2**21
         filesz 0x00000000010a9968 memsz 0x00000000010a9968 flags r-x
    LOAD off    0x00000000010a9f40 vaddr 0x00000000012a9f40 paddr 0x00000000012a9f40 align 2**21
         filesz 0x00000000000000c0 memsz 0x00000000000000c0 flags rw-
 DYNAMIC off    0x00000000010a9f40 vaddr 0x00000000012a9f40 paddr 0x00000000012a9f40 align 2**3
         filesz 0x00000000000000c0 memsz 0x00000000000000c0 flags rw-
   RELRO off    0x00000000010a9f40 vaddr 0x00000000012a9f40 paddr 0x00000000012a9f40 align 2**0
         filesz 0x00000000000000c0 memsz 0x00000000000000c0 flags r--

Dynamic Section:
  HASH                 0x0000000000000120
  GNU_HASH             0x000000000002c1e8
  STRTAB               0x0000000000108420
  SYMTAB               0x0000000000060240
  STRSZ                0x00000000002cd482
  SYMENT               0x0000000000000018

Sections:
Idx Name          Size      VMA               LMA               File off  Algn
  0 .hash         0002c0c4  0000000000000120  0000000000000120  00000120  2**3
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  1 .gnu.hash     00034054  000000000002c1e8  000000000002c1e8  0002c1e8  2**3
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  2 .dynsym       000a81e0  0000000000060240  0000000000060240  00060240  2**3
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  3 .dynstr       002cd482  0000000000108420  0000000000108420  00108420  2**0
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  4 .text         00cd40b6  00000000003d58b0  00000000003d58b0  003d58b0  2**4
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  5 .eh_frame     00000000  00000000010a9968  00000000010a9968  010a9968  2**3
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  6 .dynamic      000000c0  00000000012a9f40  00000000012a9f40  010a9f40  2**3
                  CONTENTS, ALLOC, LOAD, DATA
```

While I'm reasonably sure that my WASM file is corrupt in some way, I think Lucet should still raise an error or something instead of generating a malformed .so file.

**Comment by zhuowei** [comment]
I also found this related issue: having a huge number of methods also breaks object generation:

```
$ cat hugefileplease.py 
for i in range(0x10000):
	print("void func" + str(i) + "(void){}")
print("int main() {}")
$ python3 hugefileplease.py >huge.c
$ # Using wasi-sdk clang:
$ ./clang -Wl,--no-gc-sections -Wl,--export-all -o huge.wasm huge.c
$ /opt/lucet/bin/lucetc-wasi -o huge.so huge.wasm
ErrorMessage { msg: "ld of /tmp/lucetcy1iQJr/tmp.o failed: ld: /tmp/lucetcy1iQJr/tmp.o symbol number 196754 references nonexistent SHT_SYMTAB_SHNDX section\n/tmp/lucetcy1iQJr/tmp.o: error adding symbols: File format not recognized\n" }
```

**Comment by zhuowei** [comment]
It seems Faerie can't handle files with a large number of methods: filed https://github.com/m4b/faerie/issues/76.

**Comment by jedisct1** [comment]
Hi,

And thanks for reporting these two issues!

While running the resulting library causes an OOB error, it seems to build and start fine using the Lucet container.

Is it how you are compiling it? Just wondering if the system you are testing it on may have different versions of LLVM, binutils, or something else that may cause this.

**Comment by zhuowei** [comment]
@jedisct1 Thank you so much for your response!

That's odd: I'm on Ubuntu 18.04 with the system clang installed (clang-6.0), and both wasm files are linked from wasi-ld from wasi-sdk.

Are you running the minimal testcase with 0x10000 methods?

**Comment by jedisct1** [comment]
I was referring to the first issue, the Swift WASM file. That one compiles and starts, both using the Lucet container, and on macOS.

The 64k method testcase triggers the same issue, due to  the limitation in faerie that you just exposed (good catch!)

**Comment by zhuowei** [comment]
@jedisct1 huh, that's weird: let me check if I uploaded the correct test file.

Thank you so much!

**Comment by zhuowei** [comment]
@jedisct1 I [reuploaded the file](https://drive.google.com/file/d/1Iz4eSvyeZRJrpDOcN7bkAYXdKlYcEh-x/view?usp=sharing); hopefully this is the correct one.

**Comment by jedisct1** [comment]
That one fails the same way :)

Thanks for this very useful test case! We are going to investigate.

**Comment by zhuowei** [comment]
@jedisct1 Thank you so much - and sorry about the wrong file; I guess I have too many wasm files lying around...

I'm currently trying to patch Faerie to allow it to emit more than 65k sections using [SHN_LORESERVE](http://man7.org/linux/man-pages/man5/elf.5.html), which should hopefully help with this issue.

**Comment by zhuowei** [comment]
@jedisct1 I can confirm that this bug doesn't occur on macOS: Lucet can run the minimal 0x10000 function testcase on my macOS 10.14.4 computer just fine.

I tried implementing extra section support for Faerie in https://github.com/m4b/faerie/pull/77 and didn't get it to work, unfortunately.

I'm probably just going to test on macOS for now until this is resolved - thank you so much for all your help!

**Comment by pchickey** [comment]
@zhuowei thanks for working on this! I’ll see if I can make some time to work on Faerie’s elf backend, since I’ve done some other work on it, but I don’t expect to get to it in the next week or two. Thanks for narrowing it down for us!

**Comment by zhuowei** [comment]
@pchickey The author of faerie now has a pull request implementing extra sections (https://github.com/m4b/faerie/pull/78), so that should help. I haven't tested it yet though.

**Comment by jedisct1** [comment]
@zhuowei I updated our copy of Faerie to include these changes, and rebuilt lucetc.

Here are some good news: the 0x10000 function test case now passes!
