### ISSUE TITLE
fail to compile on macos and linux with the same promotion

### ISSUE THREAD

**Issue by SanJue** [fastly/lucet#175]
![image](https://user-images.githubusercontent.com/7995985/57458908-c497da80-72a4-11e9-95f6-3c76d74d6d8d.png)
linux os

**Comment by SanJue** [comment]
![image](https://user-images.githubusercontent.com/7995985/57459021-fd37b400-72a4-11e9-80e0-739de7363d7b.png)
macos

**Comment by jedisct1** [comment]
The following environment variables are required:

* `WASI_SYSROOT`: the path to your WASI sysroot installation (e.g. `/opt/wasi-sysroot`)
* `CLANG_ROOT`: the path to the clang 8 root. On MacOS, after install `llvm` with Homebrew, the path is `/usr/local/opt/llvm/lib/clang/8.0.0`.

**Comment by jedisct1** [comment]
The documentation definitely needs an update.

Thanks for the heads up!

**Comment by SanJue** [comment]
thanks!
