### ISSUE TITLE
Does lucetc support WebAssembly 1.0 fully now?

### ISSUE THREAD

**Issue by SanJue** [fastly/lucet#183]
I want to try to use lucet in my project

but I need know the status of supporting WebAssembly 1.0

if not fully supported, can I find the list of points not supported  anywhere?

**Comment by jedisct1** [comment]
Hi SanJue,

I think the main things Lucet doesn't support now are global imports, mutable globals and globals in initializers.

These are known issues that are being worked on.

**Comment by SanJue** [comment]
thanks

**Comment by SanJue** [comment]
I think this question is very important,
because it affects the decision whether lucetc could be used in production

as mentioned above, mutable globals is not supported now,
but I tried
`#include <stdio.h>

int a = 2;
int main(void)
{
    for(int i =0; i<a;i++)
    puts("Hello world");
    return 0;

}`
and got right result:
`Hello world
Hello world`

so I wolud like to know ,compare to full spec of wasm, what lucetc really lacks of

**Comment by maxmcd** [comment]
@SanJue wasm globals: https://webassembly.org/docs/semantics/#global-variables

**Comment by tyler** [comment]
Hey @SanJue! Globals in C are not actually represented as wasm globals. They're just a known location in linear memory. The bits of the wasm spec that we haven't yet implemented are all things that are not representable directly in C. So, any C program you write should work fine in Lucet.

The we've noted which spectests we're currently failing here: https://github.com/fastly/lucet/blob/master/lucet-spectest/tests/wasm-spec.rs#L30-L101.

**Comment by chmllr** [comment]
> @SanJue wasm globals: https://webassembly.org/docs/semantics/#global-variables

Could you please clarify to what extent the mutable globals are not supported? I've created a small Wasm module, declared a mutable global:

`(global (;0;) (mut i32) (i32.const 0))`

And defined a few functions setting/getting its value. Then I created a binary Wasm module and compiled it to a shared module. It works without any problems with Lucet. 

The failing tests from @tyler's have comments both mentioning _exporting_ of the globals. So do you mean that **exported** mutable globals are not supported?

Thanks!

**Comment by awortman-fastly** [comment]
so, Frank and Tyler are both right here! At the time, I think, mutable globals weren't supported yet. They should work just fine now :)

_exporting_ mutable globals is a slightly different story - as Tyler mentioned toolchains don't rely on globals much (yet?), so they're not exercised heavily. I would imagine they _work_ in as much as other globals work, mutable globals being readable and writable. Judging by the comment along with the spectests, the test likely fails right now more because a tool we use to translate between the text and binary wasm formats, `wabt`, doesn't support translating exported mutable globals. If you had the right binary from the get-go I'd be optimistic that we'd handle it acceptably.

A note here, _importing_ and _exporting_ globals is still questionable, because Lucet doesn't have any concept of dynamic linkage between wasm modules, yet. So you an have an exported mutable global, but the only things seeing it would be your module (that it's exported from) and the runtime host, which can access all globals anyway.

Some other parts of the linked spec test comments need updating as well - we pass several more parts of the spec test than are indicated there.

**Comment by SanJue** [comment]
> Hey @SanJue! Globals in C are not actually represented as wasm globals. They're just a known location in linear memory. The bits of the wasm spec that we haven't yet implemented are all things that are not representable directly in C. So, any C program you write should work fine in Lucet.
> 
> We've noted which spectests we're currently failing here: https://github.com/fastly/lucet/blob/master/lucet-spectest/tests/wasm-spec.rs#L30-L101.

this is useful for me, thank you!

**Comment by SanJue** [comment]
> so, Frank and Tyler are both right here! At the time, I think, mutable globals weren't supported yet. They should work just fine now :)
> 
> _exporting_ mutable globals is a slightly different story - as Tyler mentioned toolchains don't rely on globals much (yet?), so they're not exercised heavily. I would imagine they _work_ in as much as other globals work, mutable globals being readable and writable. Judging by the comment along with the spectests, the test likely fails right now more because a tool we use to translate between the text and binary wasm formats, `wabt`, doesn't support translating exported mutable globals. If you had the right binary from the get-go I'd be optimistic that we'd handle it acceptably.
> 
> A note here, _importing_ and _exporting_ globals is still questionable, because Lucet doesn't have any concept of dynamic linkage between wasm modules, yet. So you an have an exported mutable global, but the only things seeing it would be your module (that it's exported from) and the runtime host, which can access all globals anyway.
> 
> Some other parts of the linked spec test comments need updating as well - we pass several more parts of the spec test than are indicated there.

**Comment by SanJue** [comment]
> so, Frank and Tyler are both right here! At the time, I think, mutable globals weren't supported yet. They should work just fine now :)
> 
> _exporting_ mutable globals is a slightly different story - as Tyler mentioned toolchains don't rely on globals much (yet?), so they're not exercised heavily. I would imagine they _work_ in as much as other globals work, mutable globals being readable and writable. Judging by the comment along with the spectests, the test likely fails right now more because a tool we use to translate between the text and binary wasm formats, `wabt`, doesn't support translating exported mutable globals. If you had the right binary from the get-go I'd be optimistic that we'd handle it acceptably.
> 
> A note here, _importing_ and _exporting_ globals is still questionable, because Lucet doesn't have any concept of dynamic linkage between wasm modules, yet. So you an have an exported mutable global, but the only things seeing it would be your module (that it's exported from) and the runtime host, which can access all globals anyway.
> 
> Some other parts of the linked spec test comments need updating as well - we pass several more parts of the spec test than are indicated there.

thanks, it's useful for me!

**Comment by chmllr** [comment]
Thank you so much for clarifying this, @awortman-fastly !
