### ISSUE TITLE
Improve `lucetc` API and potentially augment with tool wrappers

### ISSUE THREAD

**Issue by acfoltzer-fastly** [fastly/lucet#19]
Right now, almost all use of `lucetc` is via the command line. For testing purposes and potentially other applications, it would be nice to use `lucetc` as a library instead.

A concrete outcome of this would be to no longer use `lucetc` in the Makefile targets for generating test guests.

Augmenting this with something that could replace `lucetcc` would also be nice, but the API surface of a C compiler is much bigger to bite off.

**Comment by pchickey** [comment]
We have this as of #32
