### ISSUE TITLE
Lucetc API to build from &[u8]

### ISSUE THREAD

**Issue by singpolyma-shopify** [fastly/lucet#193]
Right now the `Lucetc` API requires passing a file path, but on calling `build` the first thing it does is slurp all the bytes into RAM.  I understand that the main purpose of this library is to implement the `lucetc` CLI and for that it doesn't much matter, but it would be very useful to be able to embed the compiler in my app, where I already have the WASM bytecode in a `Vec<u8>` and not in a file.

Would it be reasonable to have the `Lucetc` API build from `AsRef<u8>` and move the file-slurp call either into `main.rs` or into a second constructor for `Lucetc`?

**Comment by jedisct1** [comment]
Hi,

This is a great suggestion, and definitely something we will add to the API.

Thanks!

**Comment by data-pup** [comment]
I'd like to try and take care of this :slightly_smiling_face:

**Comment by jedisct1** [comment]
Awesome, thank you @data-pup !

**Comment by acfoltzer** [comment]
Closed by #215; thanks @data-pup!
