### ISSUE TITLE
undefined symbol: lucet_vmctx_grow_memory

### ISSUE THREAD

**Issue by singpolyma-shopify** [fastly/lucet#194]
This is what I'm getting when trying to use lucet_runtime to execute an instance.

I tried adding `lucet_runtime::lucet_internal_ensure_linked();` to my `main()` but it didn't help -- any ideas what could be causing this?

**Comment by singpolyma-shopify** [comment]
Looks like this is a dupe with #73 -- the fix there worked for me.  Sorry for the noise.

**Comment by jedisct1** [comment]
No problem. Glad you figured it out :)

This is definitely something we should document. Thanks for the heads up!

**Comment by singpolyma-shopify** [comment]
So, the fix does `not` work for 'cargo build --release` even though it says it will use the `.cargo/config` `build.rustflags` in all cases.  Perhaps one of the optimizations or strippers is ruining something?

**Comment by pchickey** [comment]
can you provide a test case so we can reproduce this? We use lucet-runtime in release mode executables and I'm not sure how our setup differs from what you're seeing.

**Comment by singpolyma-shopify** [comment]
@pchickey is there any way I can send you some test code without posting it publicly?

**Comment by pchickey** [comment]
sure! send a tar file, google drive share, or whatever to phickey@fastly.com :)

**Comment by singpolyma-shopify** [comment]
So this was resolved by adding `lucet_runtime::lucet_internal_ensure_linked();` to `main()` in release mode.
