### ISSUE TITLE
README needs to be updated?

### ISSUE THREAD

**Issue by chmllr** [fastly/lucet#197]
The current "Getting started" section implies, that after these steps the `lucetc` binary should be available on the host machine:

0. `git submodule init && git submodule update`
1. Install & run the docker
2. `source devenv_setenv.sh`

However, after these steps, the `host/bin` folder contains only one output of the broken wrapper scripts created by `devenv_setenv.sh`, because `$LUCET_BIN_DIR` being set to `/opt/lucet/bin` is simply not available in the docker image.

Two additional steps I had to execute (reverse engineered from `helpers/install.sh`) before sourcing `devenv_setenv.sh`:

- `./devenv_run.sh cargo build --release`
- `./devenv_run.sh /lucet/helpers/install.sh`

After that `lucetc` appeared in the `host/bin` folder and could be executed.

I'd be happy to provide a small patch for README, but I am not entirely sure, that the problem is actually not on my side (latest macOS).

**Comment by jedisct1** [comment]
Hi,

And thanks for reporting this.

These extra commands shouldn't be necessary. `devenv_setenv.sh` calls `devenv_run.sh` that itself calls `devenv_start.sh` if the container is not started, and that command builds the container if it doesn't exist.

I'm going to check if there hasn't been a regression here. What macOS version are you running?

**Comment by jedisct1** [comment]
Unfortunately, I couldn't reproduce this. After crating `lucet-dev`, `devenv_setenv.sh` automatically creates the optimized version as expected:

```text
Successfully tagged lucet-dev:latest
Error: No such image: lucet:latest
Now creating lucet:latest on top of lucet-dev:latest
Building and installing optimized files in [/lucet]
Creating a RELEASE build
cargo build --all --release --bins --lib
...
```

What shell are you using?

I tried with Catalina that switches `bash` for `zsh`, but the optimized version was built as well.

Things can go wrong if you started to build the container and interrupted the build, or if you manually tried to build the container prior to running `devenv_setenv.sh`.

But note that the toolchain can run natively on macOS. It will run way faster than inside Docker, and doesn't have its limitations regarding filesystem visibility.

See the [compiling for macOS](https://github.com/fastly/lucet/wiki/Compiling-on-macOS) page on the Wiki for more information.

**Comment by chmllr** [comment]
Hi, and thanks for the quick response! My macOs version is 10.14.5.

A few more things which might help you:

1. I tried (twice) to rebuild the Docker container using `devenv_build_container.sh` but ti did not help.
2. I had already a working environment about a month ago, but started fresh today from the latest master. I am not a Docker expert, so I could imagine that something was cached somewhere in the Docker service from the previous setup.

**Comment by chmllr** [comment]
Thanks a lot for the latest response. I think a month ago the only choice was Docker, I also noticed that there are build instructions for macOs now, I will try them.

This seems to be the most probable cause of problems (see my previous message):

> Things can go wrong if you started to build the container and interrupted the build, or if you manually tried to build the container prior to running devenv_setenv.sh.

Thanks a lot, from my POV the issue can be closed then.

**Comment by jedisct1** [comment]
Thanks for trying Lucet!

A Homebrew formula will be available soon, so installing it on macOS will be faster and easier.
