### ISSUE TITLE
fail to run hello.c 

### ISSUE THREAD

**Issue by SanJue** [fastly/lucet#198]
![image](https://user-images.githubusercontent.com/7995985/59094462-c35fd900-8948-11e9-9102-436045a3a03a.png)
no "lucetc-wasi" at all , so i just use lucetc to compile hello.wasm

but i got
![image](https://user-images.githubusercontent.com/7995985/59142167-6c134480-89ec-11e9-8a36-c1adde510741.png)

**Comment by jedisct1** [comment]
Hi!

`lucetc-wasi` is a simple shell script that gets installed when the Docker container is used.

All it does is:

```sh
#! /bin/sh
exec "${LUCET_BIN_DIR}/lucetc" "\$@" --bindings "${LUCET_SHARE_DIR}/lucet-wasi/bindings.json"
```

That is, it adds `--bindings` and the path to the `lucet-wasi/bindings.json` file.

`--bindings` is required to define the imported functions that your application can call, and how they map to native functions. The `bindings.json` file contains the mapping for the WASI functions defined by `lucetc-wasi`.

**Comment by jedisct1** [comment]
If you are running Linux, `make install` should install everything in `$LUCET_PREFIX` (`/opt/lucet` by default), including `lucet-wasi`.

If you are running macOS, this will also be the case after #200 is merged.

**Comment by SanJue** [comment]
thanks for your reply!

I think that  some information miss in the part naming "Compilation on macOS" in READ.ME:
1.  
![image](https://user-images.githubusercontent.com/7995985/59141939-33716c00-89e8-11e9-93cd-ca6c226e616b.png)
 "make install" should be mentioned

2.  installation of https://github.com/CraneStation/wasi-sdk/releases/download/wasi-sdk-5/wasi-sdk-5.0-macos.tar.gz is not mentioned

**Comment by SanJue** [comment]
![image](https://user-images.githubusercontent.com/7995985/59142059-a380f180-89ea-11e9-8775-4d1c92378128.png)

I run the samples of "hello.c" on macos;

a. version of macos is 10.14.1

b. use the master branch of lucet

c. wasi-sdk use https://github.com/CraneStation/wasi-sdk/releases/download/wasi-sdk-5/wasi-sdk-5.0-macos.tar.gz

lucet is installed properly
![image](https://user-images.githubusercontent.com/7995985/59142104-23a75700-89eb-11e9-9a3d-ff2a974decf9.png)

wask-sdk installed as followed
![image](https://user-images.githubusercontent.com/7995985/59142116-6d903d00-89eb-11e9-9943-f90b4665f6e2.png)

**Comment by jedisct1** [comment]
The `make install` didn't support macOS until last night.

Now that it does, the Wiki page can indeed be updated.

The WASI SDK should not be installed, since LLVM and Clang have already been installed using Homebrew, and this is what the instructions assume.

All you need is the WASI sysroot.

**Comment by jedisct1** [comment]
Looks like the `make install` target is still missing some paths for macOS.

So let's not update the documentation until this is fixed.

**Comment by SanJue** [comment]
after removing wasi-sdk

I run "clang-8 hello.c  --target=wasm32-wasi --sysroot=/opt/wasi-sysroot/"
instead of "wasm32-wasi-clang -Ofast -o hello.wasm hello.c"

then, run "lucetc-wasi hello.wasm  -o hello.so",errors as before:
![image](https://user-images.githubusercontent.com/7995985/59142576-0b3b3a80-89f3-11e9-8430-46bb657ba8da.png)

**Comment by jedisct1** [comment]
`lucetc-wasi` doesn't have the correct path to the `bindings.json` file, due to `WASI_SYSROOT` not having been defined.

Can you try the `fdenis/find-llvm` branch? You would need to type `make install` again.

Instead of relying on an environment variable to find the WASI sysroo, it will try to find it automatically, as well as other paths.

**Comment by SanJue** [comment]
maybe some permisssion is not right;
but I have checked the owner of installation dir "/opt/lucetc"
and the code dir "/Users/lidw/Desktop/lucet/"

**sudo** lucetc-wasi -o hello.so hello.wasm works now;

![image](https://user-images.githubusercontent.com/7995985/59144551-341bf980-8a0c-11e9-8bd3-d26a46464d65.png)

**Comment by SanJue** [comment]
branch fdenis/find-llvm also need  use "sudo" to work

thanks for your reply!

I can explore lucetc in deep now!

and I will close this question
