### ISSUE TITLE
Serialize trap manifest and tables in `lucet-module-data`

### ISSUE THREAD

**Issue by acfoltzer-fastly** [fastly/lucet#20]
Support for these is not landing in #16, but we would eventually like all of the module metadata to live in that structure.

The main challenge here will be keeping the amount of copying down, since the trap metadata is potentially quite large. To that end, we'll probably want to keep at least the tables, but potentially also the manifest as a byte slice to allow zero-copy deserialization. We'll want to be very careful with alignment when we do that.

**Comment by awortman-fastly** [comment]
This has been moved to `ModuleData`, and both are deserialized in a [zero-copy manner](https://github.com/fastly/lucet/blob/a9a1fc0cfeb26d1344fc9bc3ebf5b9e1e9c73850/lucet-runtime/lucet-runtime-internals/src/module/dl.rs#L74). We still need to be very careful with alignment and layout if we change `FunctionSpec` or trap site layout in the future.
