### ISSUE TITLE
C API for `lucet-runtime`

### ISSUE THREAD

**Issue by pchickey** [fastly/lucet#21]
In order to deprecate lucet-runtime-c, we need to create a C API that the existing users of lucet-runtime-c can migrate to. This interface doesn't need to be compatible with the lucet-runtime-c's.

@acfoltzer-fastly experimented with using https://github.com/eqrion/cbindgen for this, but it didn't pan out. We could either try another tool, or just maintain C bindings by hand.

**Comment by acfoltzer-fastly** [comment]
Closing in favor of #79 and #80
