### ISSUE TITLE
Benchmark OptLevel seems incorrect

### ISSUE THREAD

**Issue by abrown** [fastly/lucet#216]
When I attempt to run the `benchmarks/lucet-benchmarks` through, e.g., `make bench` the build fails. It seems that on my system clang expects the optimization level to be `fastest`, not `fast`:

```
$ clang-8 --version
clang version 8.0.0 (Fedora 8.0.0-1.fc30)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /bin

$ export WASI_SYSROOT=/opt/wasi-sysroot
$ export CLANG_ROOT=/usr/lib64/clang/8.0.0
$ export CLANG=/bin/clang-8
```

When I alter `compiler.rs` (diff below) then I can build and run the benchmarks:

```
diff --git a/lucetc/src/compiler.rs b/lucetc/src/compiler.rs
index 9cc82d8..dfc4925 100644
--- a/lucetc/src/compiler.rs
+++ b/lucetc/src/compiler.rs
@@ -37,7 +37,7 @@ impl Default for OptLevel {
 impl OptLevel {
     pub fn to_flag(&self) -> &str {
         match self {
-            OptLevel::None => "fast",
+            OptLevel::None => "fastest",
             OptLevel::Standard => "default",
             OptLevel::Fast => "best",
         }
```

I have several questions:
1. Does anyone know why my system thinks the opt-level should be `fastest`? Should I make a merge request to handle this type of difference?
2. For consistency, shouldn't `OptLevel::Fast` point to `"fast"` (or `"fastest"` in my case) and `OptLevel::None` to `"best"`? And should submit a merge request for this?

**Comment by abrown** [comment]
I see a similar issue when I run the shootout portion of the benchmarks with `make -C benchmarks/shootout`:

```
.../lucet/target/release/lucetc --opt-level best --min-reserved-size 4294967296 --emit=obj \
	--bindings=bindings.json \
	--bindings=.../lucet/lucet-wasi/bindings.json \
	--builtins=.../lucet/lucet-builtins/build/libbuiltins.so build/lucet/module.wasm -o build/lucet/module.o
error: 'best' isn't a valid value for '--opt-level <opt_level>'
	[possible values: 0, 1, 2, fast]
```

**Comment by jedisct1** [comment]
Hi,

And thanks for reporting this.

This optimization level is not for `clang`, but for `cranelift`, the webassembly compiler.

With clang `-Ofast` is meant to produce the fastest code.
With cranelieft `fastest` produces the *slowest* code (but the fastest to compile).

This is a little bit confusing :) So what Lucet exposes as `None` is the `fastest` optimization level for cranelift, i.e. with no optimizations. 

Cranelift exposes `0` (cranelift's `fastest`), `1` and `2` (which is currently a synonym for `best`).

The benchmarks need to be updated.

**Comment by abrown** [comment]
@jedisct1 Thanks for the quick reply and the explanation; your pull request answers half of my build issues which is great 😄. However, from your explanation I still have the nagging feeling that we still need to change `fast` to `fastest` in `compiler.rs`--does that also need to be fixed?

**Comment by pchickey** [comment]
I think we just want to fix the Makefile in benchmarks. CI should have caught the bug before the optimization name changes got merged, not sure why it didn't.
