### ISSUE TITLE
Release lucet, provide a crate

### ISSUE THREAD

**Issue by nmattia** [fastly/lucet#226]
I'm trying to build lucet using the [nix] package manager, using the method described [here](https://github.com/NixOS/nixpkgs/issues/63653). Using git dependencies is somewhat problematic and it would be much easier to fetch lucet as a crate -- or at least to avoid submodules.

Could lucet be released on crates.io?

[nix]: https://nixos.org/nix/

**Comment by pchickey** [comment]
Yes, we'd like to do this, we just never got around to it. Thanks for the reminder!

**Comment by jedisct1** [comment]
Hi Nicolas!

Good news! 

https://crates.io/search?q=lucet

You can now find the Lucet crates `crates.io`  🎉

**Comment by nmattia** [comment]
Hi Frank, this is awesome. Thanks!

**Comment by antoinerg** [comment]
@nmattia Could you build lucet using Nix? If so, can you share the Nix expression? Thanks a lot

**Comment by nmattia** [comment]
@antoinerg yes I managed using [naersk](https://github.com/nmattia/naersk).

If you need to build lucet itself, here's how to do it: https://github.com/nmattia/naersk/blob/2d57092902c39dae5934bdbe48e1907961080009/test.nix#L58-L74

If you just require it as a dependency this should work:

``` nix
naersk.buildPackage ./path/to/code
  { buildInputs = [ cmake python3 ]; }
```
