### ISSUE TITLE
Add alternative to Travis for CI

### ISSUE THREAD

**Issue by acfoltzer-fastly** [fastly/lucet#23]
Given the news lately, it would be good to have an alternative to Travis ready to go.

**Comment by freebroccolo** [comment]
I can create a PR for azure pipelines config if there's interest in using that.

**Comment by pchickey** [comment]
We would be interested! However, at the moment we're waiting on some Fastly internal processes to see if we can add additional CI tools to projects under our github org. So I can't promise I'd be able to merge it yet, or possibly at all, depending on what our platform & tooling teams decide our path forward is. I will give you a heads up when I have an answer. We really appreciate the offer :heart:

**Comment by freebroccolo** [comment]
Sounds good. I'll give it a try. No worries if you can't merge it.

**Comment by pchickey** [comment]
Github Actions has been working since #331
