### ISSUE TITLE
Not all tests pass after compiling on Ubuntu

### ISSUE THREAD

**Issue by data-pup** [fastly/lucet#236]
After following the installation instructions* in`README.md`, under _"Compilation on Ubuntu 19.04"_, compilation works properly, but not all tests pass.

When running tests, I saw failures that looked like this:

```
$ cargo test

[...]

---- allocator_create_region stdout ----
thread 'allocator_create_region' panicked at 'module builds and loads: FileNotFound("clang-8")', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

[...]

failures:
    allocator_create_region
    allocator_create_region_and_increment
    allocator_create_two_regions
    entrypoint_callback
    entrypoint_ctype

test result: FAILED. 24 passed; 5 failed; 0 ignored; 0 measured; 0 filtered out
```
Backtraces looked like this:

```
stack backtrace:
   3: <failure::error::Error as core::convert::From<F>>::from::heca6ce2a479afb38 (0x560e0cc4ed42)
             at /home/katie/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/mod.rs:36
   4: lucet_runtime_tests::build::c_test::h9004e5105d47c8fb (0x560e0cc48b6d)
             at lucet-runtime/lucet-runtime-tests/src/build.rs:40
   5: lucet_runtime_tests::build::test_module_c::h38c87514e51206bf (0x560e0cc398f1)
             at lucet-runtime/lucet-runtime-tests/src/build.rs:12
   6: entrypoint::entrypoint_ctype::he0709040310e4314 (0x560e0cbd5dc9)
             at /home/katie/Rust/lucet/<::lucet_runtime_tests::entrypoint::entrypoint_tests macros>:235
```

Note: This was with the following environment variables set:

```
export WASI_SYSROOT=/opt/wasi-sysroot
export CLANG_ROOT=/usr/lib/llvm-8/lib/clang/8.0.0
export CLANG=clang-8
```

Potentially releveant functions:
https://github.com/fastly/lucet/blob/master/lucet-wasi-sdk/src/lib.rs#L57
https://github.com/fastly/lucet/blob/master/lucet-wasi-sdk/src/lib.rs#L191

@awortman-fastly pointed me to [this `wasi-sdk` commit](https://github.com/CraneStation/wasi-sdk/commit/49cf0e78ad774d110f40de66c569ae06f401101a), which renames `/opt/wasi/share/sysroot` to `/opt/wasi/share/wasi-sysroot`.

Sure enough, I was able to run tests properly if I ran this command:

```sh
mv /opt/wasi-sdk/share/wasi-sysroot  /opt/wasi-sdk/share/sysroot
```

Alternatively, these problems seemed to affect me if I built `wasi-sdk` from source rather than running the `tar` command in the wiki.

**Comment by data-pup** [comment]
Btw, at this point I have worked through these problems, but I wanted to point these wrinkles in the compilation instructions that I ran into :slightly_smiling_face: Keep up the good work y'all!

**Comment by jedisct1** [comment]
Hi!

The [instructions](https://github.com/fastly/lucet/wiki/Compiling-on-Linux#compilation-on-ubuntu-1904) assume that you are not extracting `wasi-sdk` in `/opt/wasi-sysroot`, but `wasi-libc`.

`wasi-sdk` is not required at all, only the clang builtins (`libclang_rt.builtins-wasm32-wasi-5.0.tar.gz`) , that are available in a dedicated package.

Maybe changing `/opt/wasi-sysroot` to `/opt/wasi-libc` in the Wiki page can help avoid the confusion.

**Comment by jedisct1** [comment]
There is also a [`Dockerfile`](https://github.com/fastly/lucet/blob/master/Dockerfile.toolchain) using these instructions, that sets up the environment, on Ubuntu 19.04.

And the command `./devenv_build_toolchain_only.sh` can be run to build an optimized Lucet image from it.

**Comment by jedisct1** [comment]
Also the `CLANG` variable may need to be an absolute path.

I'm going to update the wiki page to mention this as well.

**Comment by data-pup** [comment]
> The instructions assume that you are not extracting wasi-sdk in /opt/wasi-sysroot, but wasi-libc.

Admittedly this issue report is a week or two old, so this all happened before the switch over the the wiki.

Thanks for looking into this so quickly!

**Comment by jedisct1** [comment]
Indeed. The main `README.md` file was not updated any more while everything was being moved to the Wiki, so its instructions may have been not in sync with the code.

I updated the page to use `wasi-libc` instead of `wasi-sysroot` for clarity, and changed the `CLANG` example to use a full path.

Thanks for your feedback (again), this is very useful!
