### ISSUE TITLE
Error with DlModule

### ISSUE THREAD

**Issue by aranajhonny** [fastly/lucet#287]
I tried:
```
let module = DlModule::load("out.so").unwrap();
```
I'm getting an error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DlError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/libcore/result.rs:999:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by jedisct1** [comment]
Hi!

Is an `out.so` file actually present in the current directory?

The error may also come from a dependency. Try

```sh
ldd out.so
```

To print the dependencies. If any of these files is not present (including the dynamic linker itself) you will get that error.

**Comment by aranajhonny** [comment]
![image](https://user-images.githubusercontent.com/9091881/64479205-6529d880-d179-11e9-8d92-03559041403d.png)

**Comment by aranajhonny** [comment]
ldd src/out.so 
```
statically linked
```

**Comment by jedisct1** [comment]
Static libraries cannot be dynamically loaded. You need to create a shared library.

**Comment by aranajhonny** [comment]
i generated it by running
```
lucetc out.wasm --output out.so --bindings lucet-wasi/bindings.json --reserved-size 64MiB --opt-level 2 
```

**Comment by aranajhonny** [comment]
@jedisct1 thanks

**Comment by jedisct1** [comment]
Can you try with an absolute path, or `DlModule::load("./out.so")`?

**Comment by jedisct1** [comment]
By the way, `--bindings lucet-wasi/bindings.json` is not needed. You can simply use `lucetc-wasi` instead:

```sh
lucetc-wasi -o out.so --reserved-size 64MiB --opt-level 2 out.wasm
```

**Comment by aranajhonny** [comment]
![image](https://user-images.githubusercontent.com/9091881/64479793-b211ad00-d181-11e9-872e-aec192f8c334.png)

**Comment by aranajhonny** [comment]
https://github.com/fastly/lucet/wiki/Your-first-Lucet-application

I am using this `.wasm` example

**Comment by jedisct1** [comment]
Type `source /opt/lucet/bin/devenv_setenv.sh` (or wherever `lucet` was installed -- `/opt/lucet` is the default path).

Then, all the commands will be available in your path. In order to use WASI, use `lucetc-wasi` as documented, not `lucetc`.

**Comment by jedisct1** [comment]
Are you using Docker?

If you didn't install Lucet, and use the Docker container, type `source devenv_setenv.sh` in the Lucet source directory.

Paths in the container do not necessarily match paths in the host. If your application runs in Docker and tries to load a file using a path for the host, or the other way round, you will get that `No such file or directory` error.

**Comment by aranajhonny** [comment]
I'm going to use docker, notice if it works.

**Comment by aranajhonny** [comment]
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DlError(Custom { kind: Other, error: "/home/aranajhonny/lab/wasm-quickjs/src/qjs.so: undefined symbol: __wasi_fd_prestat_get" })', src/libcore/result.rs:999:5

```
