### ISSUE TITLE
error with lucet-runtime

### ISSUE THREAD

**Issue by lucifer-cpu** [fastly/lucet#291]
error with lucet runtime

```
let module = DlModule::load("output.so").unwrap();
let region = MmapRegion::create(1, &Limits::default()).unwrap();
```

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DlError(Custom { kind: Other, error: "output.so: undefined symbol: __wasi_fd_prestat_get" })'
```

**Comment by pchickey** [comment]
It looks like the lucet-wasi host functions didn't get linked into the executable you made. There are two things required to ensure that:

1. Call the runtime and lucet-wasi `ensure_linked` functions somewhere in your executable. The calls don't actually do anything, so putting them at the beginning of `main` is fine. Just has to be in reachable code.
https://github.com/fastly/lucet/blob/6ae5a401bfd2f3f9d9160623fd7c1312ef312de9/lucet-wasi/src/main.rs#L37-L40

2. You need to configure the linker to make all symbols available to the dynamic linker. The usual way to do this is with a `.cargo/config` file with the following flags:
```
[build]
rustflags = ["-C", "link-args=-rdynamic"]
```

**Comment by lucifer-cpu** [comment]
my executable is in c

**Comment by lucifer-cpu** [comment]
```
rustflags = ["-C", "link-args=-rdynamic"]
``` 
allready

**Comment by lucifer-cpu** [comment]
I am trying to run a project that is already written in c and compiled to wasm.
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ModuleError(IncorrectModule("error loading required symbol `lucet_module_data`: /home/aranajhonny/lab/wasm-quickjs/qjs.so: undefined symbol: lucet_module_data")
```

**Comment by lucifer-cpu** [comment]
Do you have any examples of any complete project written in c that runs with this runtime?

**Comment by jedisct1** [comment]
Can you run it with lucet-wasi?

**Comment by lucifer-cpu** [comment]
![image](https://user-images.githubusercontent.com/55155340/64656195-4b47fa00-d3f4-11e9-80ee-5b9577348a33.png)

**Comment by awortman-fastly** [comment]
are `output.so` and `qjs.so` above both the same file?

**Comment by lucifer-cpu** [comment]
yes

**Comment by lucifer-cpu** [comment]
Maybe I'm doing something wrong, I'm not very expert.

**Comment by awortman-fastly** [comment]
The next thing I'd suggest trying is seeing if you can run `lucet-wasi qjs.so` to double check that both work the same. For the `lucet_module_data` error, you can verify that the symbol does or doesn't exist with `objdump` - you can do something like this:
```
> objdump -x a.out | grep lucet_module_data
0000000000201000 l     O .data	0000000000001177 lucet_module_data
```

`lucet_module_data` will be present in artifacts from `lucetc`, and *must* be present for for `DlModule` to understand how to load the file. The `undefined symbol: lucet_module_data` error you saw is usually an indication that the file that it tried loading didn't come from `lucetc`.

**Comment by lucifer-cpu** [comment]
```
 objdump -x qjs.so | grep lucet_module_data
00000000005eceb0 l     O .data	0000000000024ed2 lucet_module_data

```

**Comment by jedisct1** [comment]
Here's an example of how to run a compiled WebAssembly module using Lucet:

```rust
use lucet_runtime::*;
use lucet_wasi::*;

fn main() {
    lucet_wasi::hostcalls::ensure_linked();
    let dl_module = DlModule::load("a.out").unwrap();
    let region = MmapRegion::create(1, &Limits::default()).unwrap();
    let mut instance = region.new_instance(dl_module).unwrap();
    let wasi_ctx = WasiCtx::new(&[]);
    instance.insert_embed_ctx(wasi_ctx);
    instance.run("entrypoint", &[]).unwrap();
}
```

**Comment by lucifer-cpu** [comment]
thanks but I always get the same result
```
IncorrectModule("error loading required symbol `lucet_module_data`: a.out: undefined symbol: lucet_module_data"))', src/libcore/result.rs:999:5
```

**Comment by lucifer-cpu** [comment]
https://github.com/lucifer-cpu/lucet-demo

**Comment by lucifer-cpu** [comment]
@awortman-fastly @jedisct1 It works, thanks for your patience and help.
