### ISSUE TITLE
Growing memory beyond maximum limit does not fail

### ISSUE THREAD

**Issue by lostman** [fastly/lucet#303]
Given the following module:
```
(module
  (import "env" "memory" (memory 1 1))
  (func $main (export "main")
    (i32.store (i32.const 0) (grow_memory (i32.const 1)))
  )
)
```
I expected the following test to fail: 
```
// lucet-runtime-tests/src/memory.rs
#[test]
fn grow_memory_beyond_max_size_hostcall() {
    let module = test_module_wasm("memory", "grow_memory_beyond_max_size.wat")
        .expect("compile and load grow_memory_beyond_max_size.wat");
    let region = TestRegion::create(1, &Limits::default()).expect("region can be created");
    let mut inst = region
        .new_instance(module)
        .expect("instance can be created");

    inst.run("main", &[]).expect("instance runs");
}
```
However, it completes successfully.

Shouldn't `inst.run` return `LimitsExceeded` `Error`?

**Comment by acfoltzer** [comment]
Hi @lostman,

This is actually working as expected. The semantics of the Wasm `grow_memory` instruction are that it returns `-1` if it is unable to allocate the requested memory. So, the result of the `(grow_memory (i32.const 1))` expression is `-1`, which then gets stored at linear memory address `0`, and then `main` returns normally.

Other interfaces for changing the heap size, such as `Instance::grow_memory()` do return a `LimitsExceeded` error if the request is too large, but we translate that error to a `-1` if the call is coming from a `grow_memory` instruction running in the guest.

I'm going to go ahead and close this issue, but feel free to ask any follow-up questions, and thanks for checking out Lucet :slightly_smiling_face:

**Comment by lostman** [comment]
@acfoltzer Thank you for clarification. That makes sense.
