### ISSUE TITLE
DlError following wiki "Getting Started": "hello.so: undefined symbol: lucet_vmctx_grow_memory"

### ISSUE THREAD

**Issue by vvuk** [fastly/lucet#360]
Following the "Your first application" instructions here: https://github.com/fastly/lucet/wiki/Your-first-Lucet-application

I end up with:

```
vladimir@frost:~/proj/lucet/hello$ wasm32-wasi-clang -Ofast -o hello.wasm hello.c
vladimir@frost:~/proj/lucet/hello$ lucetc-wasi -o hello.so hello.wasm
vladimir@frost:~/proj/lucet/hello$ file hello.so
hello.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, not stripped
vladimir@frost:~/proj/lucet/hello$ file hello.wasm
hello.wasm: WebAssembly (wasm) binary module version 0x1 (MVP)
vladimir@frost:~/proj/lucet/hello$ lucet-wasi hello.so
thread 'main' panicked at 'module can be loaded: DlError(Custom { kind: Other, error: "/lucet/hello/hello.so: undefined symbol: lucet_vmctx_grow_memory" })', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I see some bits like issue #73 and #194 -- but those are both with Rust, and I don't see any info on how to get the symbols linked to the C-based .so.

**Comment by awortman-fastly** [comment]
`lucet_vmctx_grow_memory` in fact will never be in the lucet-compiled .so! It's supposed to be provided by the runtime, or whatever is embedding the lucet runtime. In this case, that's `lucet-wasi`, but in the other issues you found, it was a custom rust program that embedded lucet-runtime. 

Since `lucet_vmctx_grow_memory` isn't being found, give the following `objdump` a try and see if it reports the same for your `lucet-wasi`:
```
> objdump -x lucet-wasi | grep vmctx_grow_memory
0000000000124f00 g     F .text	00000000000000c7              lucet_vmctx_grow_memory
```

Additionally, what Rust version did you use to build `lucet-wasi`?

**Comment by joeshaw** [comment]
I've been able to reproduce this as well.  I don't get a match for `lucet_vmctx_grow_memory` but I do get a mangled name:

```
root@2b396d70ebfa:/lucet# objdump -x /opt/lucet/bin/lucet-wasi | grep grow
00000000002b00a0 l     F .text	00000000000000c3              __rbt_backtrace_vector_grow
00000000003899c0 l     F .text	00000000000000aa              __rdos_backtrace_vector_grow
000000000014d6a0 g     F .text	000000000000027b              _ZN23lucet_runtime_internals8instance8Instance11grow_memory17h9c2fabcb974f5336E
000000000015c4e0 g     F .text	0000000000000029              _ZN23lucet_runtime_internals5vmctx5Vmctx11grow_memory17h1efd60a941cf9dacE
```

I'm running on a Mac, but I assume the Rust toolchain being used is the one in the docker container, right?  If so,

```
root@2b396d70ebfa:/lucet# rustc --version
rustc 1.39.0-nightly (6ef275e6c 2019-09-24)
```

**Comment by awortman-fastly** [comment]
If you can, please grab the branch in #362 (`aw/lucet-wasi-ensure-linked`), rebuild lucet-wasi, and try again.

**Comment by vvuk** [comment]
Yep, that branch fixes the issue for me. Thanks!
