### ISSUE TITLE
Fix up and release lucet-analyze

### ISSUE THREAD

**Issue by tyler** [fastly/lucet#86]
`lucet-analyze` is semi-broken since the introduction of module-data and various other minor changes. Once #20  is done, we should use module-data to clean up the lucet-analyze code and release it.

**Comment by pchickey** [comment]
worth noting that https://github.com/fastly/lucet/pull/44 will break it much more than it is broken now

**Comment by jedisct1** [comment]
`lucet-analyze` has been fixed up and released.
