### ISSUE TITLE
Documentation for Windows

### ISSUE THREAD

**Issue by freebroccolo** [fastly/lucet#87]
It would be nice to document how to build this project for developers using Windows.

I'm not sure what all the scripts are doing yet but the project at least builds with `cargo build --all --release --bins --lib` under WSL/Ubuntu `18.04.2` after having followed the steps in the `Dockerfile`.

It should be possible to use [Docker for Windows](https://docs.docker.com/docker-for-windows/) via Hyper-V. If there is interest, I could try to write some equivalent powershell scripts to make this easier.

**Comment by pchickey** [comment]
Cool! None of the project developers at Fastly use a windows machine currently. If the example code in `README.md` works under windows, and we can setup CI to make sure that the windows support doesn't break without us noticing, I'd be happy to make this part of our official docs.
